Write a function called best that take two arguments: the 2-character abbreviated name of a state and an
outcome name. The function reads the outcome-of-care-measures.csv file and returns a character vector
with the name of the hospital that has the best (i.e. lowest) 30-day mortality for the specified outcome
in that state. The hospital name is the name provided in the Hospital.Name variable. The outcomes can
be one of "heart attack", "heart failure", or "pneumonia". Hospitals that do not have data on a particular
outcome should be excluded from the set of hospitals when deciding the rankings.


```{r}
install.packages("dplyr")
library(dplyr)

best <- function(state, outcome) {
        data <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
        ## Read outcome data
        
        ## Check that state and outcome are valid
        if (state %in% data$State & outcome %in% c("heart failure","heart attack","pneumonia")){
                if(outcome=="heart attack"){
                        a<-data[,c(2,7,11)] ## specifying columns for "heart attack"
                }
                
                if(outcome=="heart failure"){
                        a<-data[,c(2,7,17)]
                }
                
                if(outcome=="pneumonia"){
                        a<-data[,c(2,7,23)]
                }
                ## Return hospital name in that state with lowest 30-day death
                b<-split(a,a$State)
                c<-b[[state]]
                c<-c[,c(1,3)]
                colnames(c)<-cbind('Hospital.Name',outcome)
                c[,2]<-as.numeric(c[,2])
                
                d<- c[which(c[,2]==min(c[,2],na.rm=TRUE)),]
                
                best_hospitals<-d$Hospital.Name
                best_hospital<-sort(best_hospitals)[1]
                
        }
        ## rate
        else if (state %in% data$State ==FALSE) { stop("invalid state")}
        
        else if (outcome %in% c("heart failure","heart attack","pneumonia")==FALSE){
                stop("invalid outcome")
        }
        
        best_hospital   
        
}
best("SC", "heart attack")

